back:
  host: manuchap.herokuapp.com
  handle: thoughtless-drylands-9499
  email: admin@studiowan.fr
  api_key: bb3be4f0209440288523f2b4ed6894fe2dd868d3

home:
  host: 0.0.0.0:5000
  handle: moonlit-grove-7470
  email: manuchap@gmail.com
  api_key: bc4b7ffa2f71ca9a9c3bf0ca12a35d1bc8c94526
