google:
  label: Google
  fields:
    site_verification_code:
      hint: Google Search Console site verification code
      type: string
comments:
  label: Intensedebate api key
  fields:
    application_id:
      type: string
      hint: 'Get it <a href="https://intensedebate.com/edit-user-account" target="_blank">here</a>.'
