title:
  en: 'TGV: Train with Great Velocity'
  fr: 'TGV: Train à Grande Vitesse'
home:
  en: Home
  fr: Accueil
hello:
  en: Hello
  fr: Bonjour
guest:
  en: guest
  fr: invité
come:
  en: It's&nbsp;coming...
  fr: Il&nbsp;arrive...
boar:
  en: Welcome&nbsp;aboard!
  fr: Bienvenue&nbsp;à&nbsp;bord!
wel1:
  en: "Welcome to the #1 LocomotiveCMS ressources website."
  fr: "Bienvenue sur le site #1 de ressources pour LocomotiveCMS."
wel2:
  en: <strong>Signup</strong> or <strong>signin</strong> to upload your ressources and share them with the world.
  fr: <strong>Incrivez vous</strong> ou <strong>connectez vous</strong> pour partager vos ressources avec le monde.
wel3:
  en: <strong>Thank you!</strong> You can now access your account and start sharing.
  fr: <strong>Incrivez vous</strong> ou <strong>connectez</strong> vous pour partager vos ressources avec le monde.
haha:
  en: "Either stick your ear to the rails or just use the menu on the left \U0001F913."
  fr: "Collez votre oreille sur les rails ou utilisez le menu de gauche \U0001F913."
whos:
  en: by
  fr: par
siin:
  en: Sign in
  fr: Connexion
siup:
  en: Signup
  fr: Inscription
subm:
  en: Submit
  fr: Envoyer
sear:
  en: Search
  fr: Chercher
push:
  en: Pushed
  fr: Propulsé
time:
  en: in
  fr: en
code:
  en: Coded
  fr: Codé
clot:
  en: Clothed
  fr: Habillé
weee:
  en: We
  fr: Nous
sour:
  en: Source
  fr: Source
demo:
  en: Demo
  fr: Demo
back:
  en: Back to the list
  fr: Retour à la liste
bksi:
  en: Go back to the sign in page
  fr: Retour à la connexion
wcre:
  en: Wrong credentials!
  fr: Mauvais identifiants!
wmai:
  en: Wrong email!
  fr: Mauvais email!
name:
  en: Your name
  fr: Votre nom
mail:
  en: Your E-mail
  fr: Votre E-mail
pass:
  en: Password
  fr: Mot de passe
pasc:
  en: Password confirmation
  fr: Mot de passe à nouveau
forg:
  en: Forgot your password?
  fr: Mot de passe oublié?
disc:
  en: You've been disconnected!
  fr: Vous êtes déconnecté!
auth:
  en: You're already authenticated!
  fr: Vous êtes déjà connecté!
sorr:
  en: We're sorry, we couldn't create your account.
  fr: Votre compte ne peut pas être créé.
sent:
  en: The instructions for changing your password have been emailed to you.
  fr: Les instructions de changement de mot de passe vous ont été envoyées.
