siin:
  en: Sign in
  fr: Connexion
siup:
  en: Signup
  fr: Inscription
sear:
  en: Search
  fr: Chercher
push:
  en: Pushed
  fr: Propulsé
time:
  en: in
  fr: en
forg:
  en: Forgot your password?
  fr: Mot de passe oublié?
disc:
  en: You've been disconnected!
  fr: Vous êtes déconnecté!
auth:
  en: You're already authenticated!
  fr: Vous êtes déjà connecté!
title:
  en: 'TGV: Train with Great Velocity'
  fr: 'TGV: Train à Grande Vitesse'
home:
  en: Home
  fr: Accueil
hello:
  en: Hello
  fr: Bonjour
guest:
  en: guest
  fr: invité
whos:
  en: by
  fr: par
code:
  en: Code
  fr: Code
clot:
  en: Clothed
  fr: Habillé
weee:
  en: We
  fr: Nous
sour:
  en: Source
  fr: Source
demo:
  en: Demo
  fr: Demo
back:
  en: Back to the list
  fr: Retour à la liste
wcre:
  en: Wrong credentials!
  fr: Mauvais identifiants!
name:
  en: Name
  fr: Nom
mail:
  en: Your E-mail
  fr: Votre E-mail
pass:
  en: Password
  fr: Mot de passe
pasc:
  en: Password confirmation
  fr: Mot de passe à nouveau
sorr:
  en: We're sorry, we couldn't create your account.
  fr: Votre compte ne peut pas être créé.
come:
  en: It's&nbsp;coming...
  fr: Il&nbsp;arrive...
boar:
  en: Welcome&nbsp;on&nbsp;board!
  fr: Bienvenue&nbsp;à&nbsp;bord!
wel1:
  en: 'Welcome to the #1 LocomotiveCMS ressources website.'
  fr: 'Bienvenue sur le site #1 de ressources pour LocomotiveCMS.'
wel2:
  en: "<strong>Signup</strong> or <strong>signin</strong> to upload your ressources
    and share them with the world."
  fr: "<strong>Incrivez vous</strong> ou <strong>connectez vous</strong> pour partager
    vos ressources avec le monde."
wel3:
  en: "<strong>Thank you!</strong> You can now access <strong>your account</strong>
    and start sharing."
  fr: "<strong>Merci!</strong> Vous pouvez à présent accéder à <strong>votre compte</strong>
    et commencer à partager."
haha:
  en: "Either stick your ear to the rails or just use the menu on the left \U0001F913."
  fr: "Collez votre oreille sur les rails ou utilisez le menu de gauche \U0001F913."
subm:
  en: Submit
  fr: Envoyer
bksi:
  en: Go back to the sign in page
  fr: Retour à la connexion
wmai:
  en: Wrong email!
  fr: Mauvais email!
sent:
  en: The instructions for changing your password have been emailed to you.
  fr: Les instructions de changement de mot de passe vous ont été envoyées.
hihi:
  en: "Please take a seat, open your laptop and start coding  \U0001F913."
  fr: "Veuillez prendre place, ouvrez votre portable et codez \U0001F913."
myac:
  en: My account
  fr: Mon compte
yrac:
  en: Your account
  fr: Votre compte
mysh:
  en: My shares
  fr: Mes partages
ynam:
  en: Your name
  fr: Votre nom
repa:
  en: Reset password
  fr: Changer de mot de passe
nact:
  en: New action
  fr: Nouvelle action
dact:
  en: Delete action
  fr: Supprimer l'action
uact:
  en: Edit action
  fr: 2diter l'action
desc:
  en: Description
  fr: Description
tras:
  en: Trash
  fr: Corbeille
dele:
  en: Your deleted files are still on the server.
  fr: Vos fichier supprimés sont encore sur le serveur.
ctcz:
  en: Contact
  fr: Contactez
iman:
  en: me
  fr: moi
reco:
  en: to recover them.
  fr: pour les récupérer
warn:
  en: "(your ip's being recorded, abusers will be banned.)"
  fr: "(votre ip est enregistrée, tout abus sera banni)"
codd:
  en: Coded
  fr: Codé
napp:
  en: New app
  fr: Nouvelle app
next:
  en: Next
  fr: Suivant
ngis:
  en: New gist
  fr: Nouveau gist
nmis:
  en: New misc
  fr: Nouveau misc
ntem:
  en: New template
  fr: Nouveau template
nvid:
  en: New video
  fr: Nouvelle vidéo
orig:
  en: Origin
  fr: Origine
pict:
  en: Picture
  fr: Image
prev:
  en: Previous
  fr: Précédent
publ:
  en: Published
  fr: Publié(e)
type:
  en: Type
  fr: Type
